language: rust
cache:
  - $HOME/.cache
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libtool
rust:
  - stable
  - beta
  - nightly
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - which rustfmt || cargo install rustfmt
  - mkdir -p $HOME/.cache && cd $HOME/.cache && wget https://github.com/grpc/grpc/archive/v1.2.5.tar.gz && tar xf v1.2.5.tar.gz && cd grpc-1.2.5 && env prefix=$HOME/.cache/ make && env prefix=$HOME/.cache make install
script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test --all
