language: rust
cache:
  - $HOME/.cache
os:
  - linux
  - osx
addons:
  apt:
    packages:
    - build-essential
    - autoconf
    - libtool
    - git
rust:
  - stable
  - beta
  - nightly
before_script:
  - export PATH="$PATH:$HOME/.cargo/bin"
  - export LD_LIBRARY_PATH="$HOME/.cargo/lib"
  - export LIBRARY_PATH="$HOME/.cargo/lib"
  - which rustfmt || cargo install rustfmt
  - which grpc_cpp_plugin || git clone https://github.com/grpc/grpc.git && cd grpc && git checkout v1.2.5 && git submodule update --init && env prefix=$HOME/.cache/ make && env prefix=$HOME/.cache make install
script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test --all
